version: "3.7"

x-common: &common
  restart: always
  logging:
    options:
      max-size: "10m"
      max-file: "10"
  networks:
    - dsp

services:
  registry:
    <<: *common
    image: dsp/discovery
    container_name: registry
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=registry
        - PORT=8761
    ports:
      - "8761:8761"

  gateway:
    <<: *common
    image: dsp/gateway
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=gateway
        - PORT=8050
    ports:
      - "8050:8050"
    depends_on:
      - registry

  auth:
    <<: *common
    image: dsp/auth
    container_name: auth
    build:
      context: .
      dockerfile: ./jdk11/Dockerfile
      args:
        - SERVICE_NAME=auth
        - PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - registry

  dbauth:
    <<: *common
    image: mysql
    container_name: dbauth
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_ROOT_PASSWORD: mysql12345
      MYSQL_USER: nguyennamhan
      MYSQL_PASSWORD: mysql12345
    ports:
      - "9907:3306"
    volumes:
      - ./auth/db/db.sql:/docker-entrypoint-initdb.d/dump.sql
networks:
  dsp:
    name: dsp_network
    driver: bridge